sonar.projectKey=achingono_money
sonar.projectName=money
sonar.projectVersion=1.0

sonar.sources=code
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.d.ts,**/spa/e2e/**

sonar.sourceEncoding=UTF-8
