sonar.projectKey=achingono_money
sonar.projectName=money
sonar.projectVersion=1.0

sonar.sources=code
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.d.ts,**/spa/e2e/**
sonar.tests=code/api/src,code/spa/src,code/spa/e2e,code/worker/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
sonar.javascript.lcov.reportPaths=code/api/coverage/lcov.info,code/spa/coverage/lcov.info,code/worker/coverage/lcov.info

sonar.sourceEncoding=UTF-8
